pipline{
    stages{
        stage("Git CheckOut"){
            steps{
                script{
                     git branch: 'main', url: 'https://github.com/MateenShaikh640/Devops_Projects.git'
                }
            }
        }
    }
}