@Library('my-shared-library') _

pipeline{

    agent any

    environment {
        JENKINS_FILE_PATH = 'Java_app/Jenkinsfile'
    }

    stages{
        
        stage("Load Jenkinsfile") {
            steps {
                script {
                    // Load and execute the Jenkinsfile using the environment variable
                    load env.JENKINS_FILE_PATH
                }
            }
        }

        stage("Git CheckOut") {

            steps{

                script{

                     gitCheckout(
                        branch: "main",
                        url: "https://github.com/MateenShaikh640/Devops_Projects.git"
                        
                     )
                     load env.JENKINS_FILE_PATH
                }
            }
        }
    }
}