@Library('my-shared-library') _

pipeline{

    agent any

    environment {
        JENKINS_FILE_PATH = 'Java_app/Jenkinsfile'
    }

    stages{

        stage("Git CheckOut") {

            steps{

                script{

                     gitCheckout(
                        branch: "main",
                        url: "https://github.com/MateenShaikh640/Devops_Projects.git"
                     )
                }
            }
        }
    }
}